### ISSUE TITLE
Banana 4 Image page 'ProgrammingError: relation "imagedata" does not exist'

### ISSUE THREAD

**Issue by ajstewart** [transientskp/banana#129]
I'm attempting to set up banana version 4 along with the version 4 of the trap, and while everything else seems to be working ok, I've having trouble with anything that accesses the fits file, such as clicking on the individual image pages. I get the error below.

I'm using the trap installed from pypi (4.0rc1) and the latest master branch of banana4.

```
[24/May/2017 15:30:52] "GET /postgres_adam_ncp2017_trap4/images/?dataset=2 HTTP/1.1" 200 13511
Internal Server Error: /postgres_adam_ncp2017_trap4/image/4/
Traceback (most recent call last):
  File "/home/stewart/.virtualenvs/banana4/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/stewart/.virtualenvs/banana4/local/lib/python2.7/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/stewart/bin/banana4/banana/views/mixins.py", line 29, in dispatch
    return super(HybridTemplateMixin, self).dispatch(*args, **kwargs)
  File "/home/stewart/.virtualenvs/banana4/local/lib/python2.7/site-packages/django/views/generic/base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/stewart/.virtualenvs/banana4/local/lib/python2.7/site-packages/django/views/generic/list.py", line 174, in get
    context = self.get_context_data()
  File "/home/stewart/bin/banana4/banana/views/details.py", line 36, in get_context_data
    self.get_size())
  File "/home/stewart/bin/banana4/banana/image.py", line 95, in extracted_sources_pixels
    hdu = reconstruct_fits(image)
  File "/home/stewart/bin/banana4/banana/image.py", line 20, in reconstruct_fits
    if not db_image.data.fits_header or not db_image.data.fits_data:
  File "/home/stewart/.virtualenvs/banana4/local/lib/python2.7/site-packages/django/db/models/fields/related.py", line 470, in __get__
    rel_obj = self.get_queryset(instance=instance).get(**params)
  File "/home/stewart/.virtualenvs/banana4/local/lib/python2.7/site-packages/django/db/models/query.py", line 328, in get
    num = len(clone)
  File "/home/stewart/.virtualenvs/banana4/local/lib/python2.7/site-packages/django/db/models/query.py", line 144, in __len__
    self._fetch_all()
  File "/home/stewart/.virtualenvs/banana4/local/lib/python2.7/site-packages/django/db/models/query.py", line 965, in _fetch_all
    self._result_cache = list(self.iterator())
  File "/home/stewart/.virtualenvs/banana4/local/lib/python2.7/site-packages/django/db/models/query.py", line 238, in iterator
    results = compiler.execute_sql()
  File "/home/stewart/.virtualenvs/banana4/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 840, in execute_sql
    cursor.execute(sql, params)
  File "/home/stewart/.virtualenvs/banana4/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/home/stewart/.virtualenvs/banana4/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/home/stewart/.virtualenvs/banana4/local/lib/python2.7/site-packages/django/db/utils.py", line 98, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/home/stewart/.virtualenvs/banana4/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
ProgrammingError: relation "imagedata" does not exist
LINE 1: ...data"."fits_header", "imagedata"."fits_data" FROM "imagedata...
                                                             ^
```

**Comment by gijzelaerr** [comment]
ah, you should use 4.0. I've updated the TKP installation in pypi, please update.

images are now stored in SQL, not in MongoDB. There will be a slowdown if the dataset is huge but now you can get rid of MongoDB as storage.
